version: "3"

services:
  backup:
    image: mev-geth
    restart: unless-stopped
    ports:
      - "172.18.194.13:30304:30304"
      - "172.18.194.13:30304:30304/udp"
      - "172.18.194.13:7891:7891"
      - "172.18.194.13:7892:7892"
    volumes:
      - /eth:/eth
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --port=30304
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.port=7891
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.port=7892
      - --ws.api
      - "eth,net,web3"
      - --datadir
      - "/eth/mev"
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      - --cache=16384
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      - --maxpeers=50
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=fast
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      # - --gcmode=full
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
