version: "3"

services:

  geth:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ${PWD}/.ethereum:/root/.ethereum
    expose:
      - "8545"
    networks: 
      - eth
    command:
      - --rpc
      - --rpcapi
      - "eth,txpool,web3"
      - --rpcaddr
      - geth
      - --rpcvhosts=*
      - --cache=1024

  nginx:
    image: "nginx:alpine"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/auth.txt:/etc/nginx/auth.txt:ro
      - ${PWD}/log:/var/log/nginx
    networks:
      - eth
    depends_on:
      - geth

networks:
  eth:
