version: "3"

services:
  geth:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "7891:7891"
      - "7892:7892"
    volumes:
      - ./eth:/master
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.port=7891
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.port=7892
      - --ws.api
      - "eth,net,web3"
      - --datadir
      - "/eth/master"
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      - --cache=32768
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      - --maxpeers=150
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=fast
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      # - --gcmode=full
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
