version: "2.4"
networks:
  nodetestnet:
    driver: macvlan
    driver_opts:
      com.docker.network.enable_ipv4: "true"
      parent: eth3
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.194.1

services:
  testnet:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - "30304:30304"
      - "30304:30304/udp"
      - "7891:7891"
      - "7892:7892"
    networks:
      nodetestnet:
        ipv4_address: 172.18.194.17
    volumes:
      - /data:/data
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --port=30304
      - --ropsten
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.port=7891
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.port=7892
      - --ws.api
      - "eth,net,web3"
      - --datadir
      - "/data/testnet"
      # Minimum number of executable transaction slots guaranteed per account (default: 16)
      # - --txpool.accountslots=16
      # Maximum number of non-executable transaction slots for all accounts (default: 1024)
      # --txpool.globalqueue=1024
      # Maximum number of executable transaction slots for all accounts (default: 4096)
      # - --txpool.globalslots=10000
      # Maximum amount of time non-executable transaction are queued (default: 3h0m0s)
      # - --txpool.lifetime=3h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      - --cache=8192
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      - --maxpeers=50
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=fast
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      # - --gcmode=full
    links:
      - geth
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
    testnet:
        driver: macvlan
        driver_opts:
            com.docker.network.enable_ipv4: "true"
            parent: eth3
        ipam:
            config:
                - subnet: 192.168.2.0/24
                  gateway: 192.168.2.1