version: "3"
services:
  bitcoind:
    image: bitcoinsv/bitcoin-sv
    # specify additional command line arguments here
    command: bitcoind -txindex -rpcport=8332 -rest -rpcthreads=10 -zmqpubrawtx=tcp://0.0.0.0:28332
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      # change to 18333 if running testnet, or 9333 if running on STN
      - "172.19.32.18:8332:8332"
      - "172.19.32.18:8333:8333"
      - "172.19.32.18:28332:28332"
    volumes:
      - /data/bsv:/data
  # bitcoin-cli:
  #   image: bitcoinsv/bitcoin-sv
  #   entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
  #   command: "getinfo"
  #   depends_on:
  #     - bitcoind
  #   network_mode: service:bitcoind
