version: "3"
services:
  bitcoind:
    image: bitcoinsv/bitcoin-sv
    # specify additional command line arguments here
    command: bitcoind -testnet -txindex
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      # change to 18333 if running testnet, or 9333 if running on STN
      - "18333:18333"
    volumes:
      - /eth/bsv:/data
    networks:
      - bitcoin
  bitcoin-cli:
    image: bitcoinsv/bitcoin-sv
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: "getinfo"
    depends_on:
      - bitcoind
    network_mode: service:bitcoind
  electrumx:
    image: electrumx
    environment:
      - DAEMON_URL=http://user:password@127.0.0.1:18332/
      - PEER_DISCOVERY=self
      - DB_DIRECTORY=/data
      - SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
    volumes:
      - /eth/electrumx:/data
    ports:
      - "50001:50001" # comment out to disable TCP port (plaintext)
      - "50002:50002"
      - "50004:50004"
      - "8000:8000"
    depends_on:
      - bitcoind

networks:
  bitcoin:
