version: "3"

services:
  bsv:
    image: bitcoinsv/bitcoin-sv
    restart: unless-stopped
    ports:
      - "40001:40001"
      - "40002:40002"
    volumes:
      - /data:/data
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - -txindex
      - -datadir
      - "/data/bsv"
      - -excessiveblocksize=4000000000,
      - -maxstackmemoryusageconsensus=200000000
      - -maxmempool=16000
      - -rpcport=40001
      - -rest
      - -printtoconsole=0
      - -rpcuser=user
      - -rpcpassword=password
      - -zmqpubrawtx=tcp://127.0.0.1:40002
      - -rpcthreads=10
      - -maxconnections=32
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
